### ISSUE TITLE
Update to build with gcc 13

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#293]
We now only need to fix a couple function signatures to get current master branch to build with gcc 13 so we should upgrade to do this and build with gcc13 on CI.

**Comment by faithanalog** [comment]
I am building on gcc14 with these changes:

```patch
diff --git a/sources/CMakeLists.txt b/sources/CMakeLists.txt
index 332c118..2d502b6 100644
--- a/sources/CMakeLists.txt
+++ b/sources/CMakeLists.txt
@@ -70,6 +70,9 @@ add_compile_options(
   -Wno-array-bounds
 )
 
+add_compile_options($<$<COMPILE_LANG_AND_ID:CXX,GNU>:-Wno-overloaded-virtual>)
+add_compile_options($<$<COMPILE_LANG_AND_ID:CXX,GNU>:-Wno-aggressive-loop-optimizations>)
+
 add_subdirectory(Adapters)
 add_subdirectory(UIFramework)
 add_subdirectory(System)
diff --git a/sources/Foundation/T_Factory.h b/sources/Foundation/T_Factory.h
index 9bc2b03..49b0f89 100644
--- a/sources/Foundation/T_Factory.h
+++ b/sources/Foundation/T_Factory.h
@@ -9,7 +9,7 @@
 
 template <class Item> class T_Factory {
 protected:
-  virtual ~T_Factory<Item>(){};
+  virtual ~T_Factory(){};
 
 public:
   // Install the factory to use
```

I do not remember what code exactly triggers those two warnings but it was only a couple spots, i just wasn't sure what to do to fix them.

**Comment by maks** [comment]
@faithanalog Thanks! I'll see if I can find get this incorporated in soon so that we can move to building with gcc13 or even better with gcc14

**Comment by maks** [comment]
@faithanalog Thanks for the prompting for me to get a move on with this 👍🏻 

I've got a PR with a branch that now builds with GCC13: https://github.com/xiphonics/picoTracker/pull/446
and hopefully fixes the issue you had fixes for for GCC14 but I don't have GCC14 installed so if you could try it out and see if it works for you that would be great 🙏🏻

**Comment by faithanalog** [comment]
that seems to take care of pretty much everything except the opal warning

```
In file included from /tmp/picoTracker/sources/Externals/opal/opal.cpp:1:
In member function ‘void Opal::Channel::SetChannelPair(Opal::Channel*)’,
    inlined from ‘void Opal::Port(uint16_t, uint8_t)’ at /tmp/picoTracker/sources/Externals/opal/opal.cpp:252:34:
/tmp/picoTracker/sources/Externals/opal/opal.h:141:54: error: iteration 1 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
  141 |     void SetChannelPair(Channel *pair) { ChannelPair = pair; }
      |                                          ~~~~~~~~~~~~^~~~~~
/tmp/picoTracker/sources/Externals/opal/opal.cpp: In member function ‘void Opal::Port(uint16_t, uint8_t)’:
/tmp/picoTracker/sources/Externals/opal/opal.cpp:238:25: note: within this loop
  238 |       for (int i = 0; i < 6; i++, mask <<= 1) {
      |                       ~~^~~
```

I really could not make sense of what the problem is that needs to be fixed, the code is a bit convoluted to me

**Comment by maks** [comment]
@faithanalog  thanks again for testing this out. I couldn't reproduce the issue after I installed and build with GCC 14.2 but just in case I pushed up a small change that should disable that warning for just the OPAL directory. If you could please let me know if that works for you and I will then look to get our CI updated to at least GCC13 and the PR merged.

**Comment by faithanalog** [comment]
@maks yup, it now builds for me now!
